networks:
  ls:
    ipam:
      config:
        # Specify the subnet range for IP address allocation
        - subnet: 10.0.2.0/24

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.8.1
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - LOCALSTACK_HOST=localhost.localstack.cloud  # set this env var to expose localstack to other containers
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_DEFAULT_REGION=eu-west-1
      - SERVICES=dynamodb,sns,sqs,lambda,s3
      # ---
      - DEBUG=${DEBUG-}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./tmp}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./src/test/resources/localstack/local-aws-infrastructure.sh:/etc/localstack/init/ready.d/init-aws.sh # ready hook
    networks:
      ls:
        # Set the container IP address in the 10.0.2.0/24 subnet
        ipv4_address: 10.0.2.20
  app:
    platform: linux/amd64
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      localstack:
        condition: service_healthy
    ports:
      - "8080:8080"
    dns:
      # Set the DNS server to be the LocalStack container
      - 10.0.2.20
    networks:
      - ls