version = 0.1
[default.deploy.parameters]
stack_name = "spring-boot-lambda-sam-app"
resolve_s3 = true
s3_prefix = "spring-boot-lambda-sam-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
